# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=200)),
                ('quiz_name', models.CharField(max_length=200)),
                ('quiz_description', models.CharField(max_length=1000)),
                ('quiz_creation_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='quiz datetime')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tagged_quiz', models.ManyToManyField(to='service.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_creation_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation datetime')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.User'),
        ),
    ]
