# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='event_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_description',
            field=models.TextField(verbose_name='Quiz description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=200, verbose_name='Quiz Name'),
        ),
        migrations.AlterField(
            model_name='quiztag',
            name='tag_name',
            field=models.CharField(max_length=50, verbose_name='Quiz Tag Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Username Email'),
        ),
    ]
