# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 21, 50, 30, 339375, tzinfo=utc), verbose_name='quiz datetime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 21, 50, 30, 322046, tzinfo=utc), verbose_name='creation datetime'),
        ),
    ]
