# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20160925_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='event_end',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
